name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (SAST)
         run: |
          pip install bandit
          bandit -r . -f json -o bandit_results.json

      - name: Upload Bandit Report
          uses: actions/upload-artifact@v3
          with:
            name: bandit-report
            path: bandit_results.json

      - name: Run unit tests
        run: |
          python -m pytest 